### PR TITLE
Merge Branch `Patch 1`

### PR DESCRIPTION
**Pull request by ghost**
Patch 1 includes the following changes:

- Add GNU GPL V3 as the Library's License
- Changed `dimooperChannel` in default.nix to `grossChannel`

Don't Judge Me. I'm Picky.

### CODE REVIEW

**Comment by rexim** [comment]
It's up to the author to decide which license he wants to release his work under. Sorry, your PR is rejected.

**Comment by ghost** [comment]
;(

**Comment by ghost** [comment]
Sorry Bout That.

**Comment by rexim** [comment]
@lorenzoi It's ok. Please don't be discouraged to contribute to this repo. Just don't decide the license for other people's work. They should decide it for themselves.

Next time if you see a repo (any repo, not only mine) without a license, don't force your license upon it. Simply create an issue saying that the license is missing. That is more right way to approach that.

Hope you have a nice day!

**Pull request closed without merging**
